### ISSUE TITLE
spot is getting launched as ondemand

### ISSUE THREAD

**Issue by pavane** [aws/aws-parallelcluster#1851] opened 2020-06-29 17:14 UTC
**Environment:**
 - AWS ParallelCluster / CfnCluster version [e.g. aws-parallelcluster-2.5.1]
aws-parallelcluster-2.7
 - Configuration file (i.e. ~/.parallelcluster/config) without any credentials or personal data.
[aws]
aws_region_name = us-east-1

[global]
cluster_template = default
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[cluster default]
key_name = mykey
placement_group = DYNAMIC
cluster_type = spot
vpc_settings = default
efs_settings = customefs
master_instance_type = t3.medium
base_os = ubuntu1804
scheduler = slurm
max_queue_size = 1 
maintain_initial_size = true

**Bug description and how to reproduce:**
I tried all the options to launch spot instances with various instance types, but instead, I get on-demand instances. 

A clear and concise description of what the bug is and the steps to reproduce the behavior.

**Additional context:**
Any other context about the problem. E.g.:
 - pre/post-install scripts, if any
 - screenshots, if useful
 - if the cluster fails creation, please re-execute `create` action using `--norollback` option and attach `/var/log/cfn-init.log`, `/var/log/cloud-init.log` and `/var/log/cloud-init-output.log` files from the Master node
 - if a compute node was terminated due to failure, there will be a directory `/home/logs/compute`. Attach one of the `instance-id.tar.gz` from that directory
 - if you encounter scaling problems please attach `/var/log/nodewatcher` from the Compute node and `/var/log/jobwatcher` and `/var/log/sqswatcher` from the Master node

**Comment by lukeseawalker** [comment] 2020-06-29 19:39
Hi @pavane,
you are not setting the compute_instance_type parameter which is using the default value of `t2.micro`.
`t2.micro` is not a supported instance type for a cluster placement group. You can check cluster placement group rules and limitations [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html#concepts-placement-groups).

Please notice that the `cluster_type` parameter applies only to the compute fleet of your cluster (not the head node).

To understand the cause of your problem you could have looked at the activity history of the autoscaling group of your cluster, with the command:
```
aws autoscaling describe-scaling-activities --region us-east-1 --query "Activities[?contains(AutoScalingGroupName, 'parallelcluster-<your_cluster_name>-ComputeFleet')]"
```

In your case you should have seen in the status message of the scaling activity something similar to:
`Cluster placement groups are not supported by the 't2.micro' instance type. Specify a supported instance type or change the placement group strategy, and try again. Launching EC2 instance failed.`

**Comment by pavane** [comment] 2020-06-29 23:10
Thank you so much. That's really very helpful.

**Comment by lukeseawalker** [comment] 2020-06-30 06:53
Were you able to move forward? Can we close this?

**Comment by pavane** [comment] 2020-06-30 17:41
I was able to. Thank you again. Please close this issue.

**Closed** 2020-07-01 05:54 UTC

**Comment by ayush-tiwari26** [comment] 2023-04-28 21:20
If ec2 t2.micro and t3.micro are not supported, which I tried, then where in the docs of AWS can I see what all ec2 instances are supported for a given class of placement group(i.e. a cluster, a spread or a partition class of placement group)?
