### ISSUE TITLE
Use customer's /home and /scratch

### ISSUE THREAD

**Issue by kim0** [aws/aws-parallelcluster#3319] opened 2021-10-07 12:31 UTC
If you are reporting an issue with AWS Parallelcluster / CfnCluster please make sure to add the following data in order to facilitate the root cause detection:

**Required Info:**
 - AWS ParallelCluster version [e.g. 2.9.0]: 3.0.0

**Bug description and how to reproduce:**
This is mostly a "help-wanted" question. I am integrating pcluster v3.0.0 into an existing environment. This environment has its own `/home/` and `/scratch` which we'd like to be mounted on compute nodes (ideally and head node). What is the best way of doing this? Currently I hack `/etc/fstab` which doesn't work well on the head node. Was wondering if there's a cleaner way of telling the cluster: Do not make your own /home and /scratch, instead mount those. 

PS: All nodes are joined to active directory upon boot using the shell script as well
Thanks!

**Comment by demartinofra** [comment] 2021-11-24 14:46
Hi @kim0 

I deeply apologize for getting back to you only now. At the moment there is no easy way to replace the shared `/home` directory since ParallelCluster relies on it for some of its functionalities. However we are actively working on adding support for active directory integration that will be available in ParallelCluster 3.1.

**Comment by kim0** [comment] 2021-11-24 14:53
@demartinofra Thanks a lot for your reply. It is good news that AD integration is planned for v3.1!

Regarding mountpoint assumptions. Can the pcluster team take a RFE to not use standard mountpoints like `/home` ? I understand the need for a home dir for certain system users, but can this use non standard paths like `/pcluster/home` or similar ? Same for `/scratch` which we also use. Let me know if this can be accepted and I can file this RFE somewhere. It's not unreasonable to think many environments will already use `/home` and want to integrate their pcluster with the environment's standard storage.

Thanks!

**Comment by demartinofra** [comment] 2021-11-24 17:58
Yes I think it's totally reasonable to drop ParallelCluster specific dependencies on the shared home and expose the possibility to not share the /home dir in cluster config.

Regarding `/scratch`, I don't think we use this path by default in any of our shared FS.

**Comment by demartinofra** [comment] 2021-11-24 18:02
Would having the possibility to mount an existing file system (EBS, EFS, FSX) on `/home` also address your use case?

**Comment by kim0** [comment] 2021-11-24 19:58
@demartinofra .. Yes! Thank you

This is precisely what I need to do. I have `/home` exported by a custom NFS server VM, and I'd like to mount that on all nodes (master and workers) without breaking cluster functionality. I hope you can support mounting from plain NFS as well as what you mentioned (EBS, EFS, FSX). 

Regarding `/scratch`, I think this was used in pcluster2, and I got confused :) Thanks a lot for your hardwork and support. Can you let me know how I can follow up the progress regarding this RFE. Regards

**Comment by MuhammadYasser2019** [comment] 2021-11-25 09:21
Hi @demartinofra 

Regarding `/scratch` , I see  EC2 machines provisioned using PClusterV3 are delivered with `/scratch`.

**How to reproduce:**

- Submitting any task on AWS PClusterv3.
- OS used Centos.
- Machine size used (z1d.large).
- Small machines like t2 don't come with `/scratch`

**Below is a clean `df` output** :
```
Filesystem                      1K-blocks       Used  Available Use% Mounted on
devtmpfs                          7928576          0    7928576   0% /dev
/dev/nvme0n1p1                   36688876   16319308   20369568  45% /
/dev/mapper/vg.01-lv_ephemeral   71959680      53272   68227996   1% /scratch
```
Regards

**Comment by demartinofra** [comment] 2021-11-26 15:33
@kim0 @MuhammadYasser2019 you are right about `/scratch` and sorry for the miss on my side. For some reason I remembered that the default mount point for instance storage was `/ephemeral` while it is `/scratch`. In any case you can control where the instance store volume gets mounted with the following config parameters: [config for HeadNode](https://docs.aws.amazon.com/parallelcluster/latest/ug/HeadNode-v3.html#yaml-HeadNode-LocalStorage-EphemeralVolume) and [config for Compute nodes](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmQueues-ComputeSettings-LocalStorage-EphemeralVolume)

**Comment by kim0** [comment] 2021-11-26 16:01
@demartinofra Awesome, thanks a lot for your help. So wrt the RFE for mounting an existing /home from NFS. How can I followup with progress please? Thanks!

**Comment by demartinofra** [comment] 2021-11-29 13:27
Issue https://github.com/aws/aws-parallelcluster/issues/2441 tracks the possibility to mount one of the shared storage options on the /home directory.

**Comment by enrico-usai** [comment] 2022-07-07 14:16
I'm closing this issue in favour of #2441. Feel free to add more comments there if needed.

**Closed by enrico-usai** 2022-07-07 14:16 UTC
Labels: enhancement
