### ISSUE TITLE
Compute nodes failing to connect to metadata service

### ISSUE THREAD

**Issue by alexiswl** [aws/aws-parallelcluster#2163] opened 2020-10-22 03:30 UTC
If you are reporting an issue with AWS Parallelcluster / CfnCluster please make sure to add the following data in order to facilitate the root cause detection:

**Required Info:**
 - AWS ParallelCluster version: 2.9.1
 - Full cluster configuration without any credentials or personal data: [Configuration Here](https://github.com/umccr/aws_parallel_cluster/blob/main/conf/config)
 - Cluster name: GPL-SBJ00575

**Bug description and how to reproduce:**
A clear and concise description of what the bug is and the steps to reproduce the behavior.

Slurm is failing health checks for nodes, which lead me to investigate their system logs on the AWS Console.
Despite slurm requesting to power these nodes down, they're continuing to stay up:
```
[2020-10-22T13:59:43.649] _slurm_rpc_kill_job: REQUEST_KILL_JOB JobId=135 uid 1000
[2020-10-22T13:59:43.649] _slurm_rpc_kill_job: REQUEST_KILL_JOB JobId=141 uid 1000
[2020-10-22T13:59:43.650] _slurm_rpc_kill_job: REQUEST_KILL_JOB JobId=136 uid 1000
[2020-10-22T13:59:43.650] _slurm_rpc_kill_job: REQUEST_KILL_JOB JobId=142 uid 1000
[2020-10-22T13:59:43.650] _slurm_rpc_kill_job: REQUEST_KILL_JOB JobId=140 uid 1000
[2020-10-22T13:59:43.651] _slurm_rpc_kill_job: REQUEST_KILL_JOB JobId=137 uid 1000
[2020-10-22T14:03:23.713] sched: _slurm_rpc_allocate_resources JobId=143 NodeList=compute-dy-c54xlarge-6 usec=434
[2020-10-22T14:03:27.672] _job_complete: JobId=143 WTERMSIG 126
[2020-10-22T14:03:27.672] _job_complete: JobId=143 cancelled by interactive user
[2020-10-22T14:03:27.672] _job_complete: JobId=143 done
[2020-10-22T14:23:29.041] node compute-dy-m54xlarge-6 not resumed by ResumeTimeout(3600) - marking down and power_save
[2020-10-22T14:23:35.956] update_node: node compute-dy-m54xlarge-6 reason set to: Scheduler health check failed
[2020-10-22T14:23:35.956] update_node: node compute-dy-m54xlarge-6 state set to DOWN
[2020-10-22T14:23:35.968] update_node: node compute-dy-m54xlarge-6 reason set to: Scheduler health check failed
[2020-10-22T14:23:35.968] power down request repeating for node compute-dy-m54xlarge-6
[2020-10-22T14:23:41.430] update_node: node compute-dy-m54xlarge-6 reason set to: Scheduler health check failed
[2020-10-22T14:23:41.431] update_node: node compute-dy-m54xlarge-6 state set to DOWN
[2020-10-22T14:23:41.442] update_node: node compute-dy-m54xlarge-6 reason set to: Scheduler health check failed
[2020-10-22T14:23:41.442] power down request repeating for node compute-dy-m54xlarge-6
[2020-10-22T14:24:32.054] node compute-dy-m54xlarge-4 not resumed by ResumeTimeout(3600) - marking down and power_save
[2020-10-22T14:24:32.054] node compute-dy-m54xlarge-5 not resumed by ResumeTimeout(3600) - marking down and power_save
[2020-10-22T14:24:41.285] update_node: node compute-dy-m54xlarge-4 reason set to: Scheduler health check failed
[2020-10-22T14:24:41.285] update_node: node compute-dy-m54xlarge-4 state set to DOWN
[2020-10-22T14:24:41.285] update_node: node compute-dy-m54xlarge-5 reason set to: Scheduler health check failed
[2020-10-22T14:24:41.285] update_node: node compute-dy-m54xlarge-5 state set to DOWN
[2020-10-22T14:24:41.296] update_node: node compute-dy-m54xlarge-4 reason set to: Scheduler health check failed
[2020-10-22T14:24:41.296] power down request repeating for node compute-dy-m54xlarge-4
[2020-10-22T14:24:41.296] update_node: node compute-dy-m54xlarge-5 reason set to: Scheduler health check failed
[2020-10-22T14:24:41.296] power down request repeating for node compute-dy-m54xlarge-5
[2020-10-22T14:24:46.814] update_node: node compute-dy-m54xlarge-4 reason set to: Scheduler health check failed
[2020-10-22T14:24:46.814] update_node: node compute-dy-m54xlarge-4 state set to DOWN
[2020-10-22T14:24:46.814] update_node: node compute-dy-m54xlarge-5 reason set to: Scheduler health check failed
[2020-10-22T14:24:46.814] update_node: node compute-dy-m54xlarge-5 state set to DOWN
[2020-10-22T14:24:46.824] update_node: node compute-dy-m54xlarge-4 reason set to: Scheduler health check failed
[2020-10-22T14:24:46.825] power down request repeating for node compute-dy-m54xlarge-4
[2020-10-22T14:24:46.825] update_node: node compute-dy-m54xlarge-5 reason set to: Scheduler health check failed
[2020-10-22T14:24:46.825] power down request repeating for node compute-dy-m54xlarge-5
~
```

```
-----END SSH HOST KEY KEYS-----
[  274.096183] cloud-init[4483]: Cloud-init v. 19.3-3.amzn2 finished at Thu, 22 Oct 2020 02:29:22 +0000. Datasource DataSourceNone.  Up 274.09 seconds
[  274.096510] cloud-init[4483]: Oct 22 02:29:22 cloud-init[4483]: cc_final_message.py[WARNING]: Used fallback datasource
[  274.396364] hibinit-agent[4484]: Traceback (most recent call last):
[  274.396571] hibinit-agent[4484]: File "/usr/bin/hibinit-agent", line 496, in <module>
[  274.396769] hibinit-agent[4484]: main()
[  274.396890] hibinit-agent[4484]: File "/usr/bin/hibinit-agent", line 435, in main
[  274.397035] hibinit-agent[4484]: if not hibernation_enabled(config.state_dir):
[  274.397177] hibinit-agent[4484]: File "/usr/bin/hibinit-agent", line 390, in hibernation_enabled
[  274.397323] hibinit-agent[4484]: imds_token = get_imds_token()
[  274.397480] hibinit-agent[4484]: File "/usr/bin/hibinit-agent", line 365, in get_imds_token
[  274.397622] hibinit-agent[4484]: response = requests.put(token_url, headers=request_header)
[  274.397762] hibinit-agent[4484]: File "/usr/lib/python2.7/site-packages/requests/api.py", line 121, in put
[  274.429270] hibinit-agent[4484]: return request('put', url, data=data, **kwargs)
[  274.429961] hibinit-agent[4484]: File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
[  274.431229] hibinit-agent[4484]: response = session.request(method=method, url=url, **kwargs)
[  274.431638] hibinit-agent[4484]: File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 486, in request
[  274.454584] hibinit-agent[4484]: resp = self.send(prep, **send_kwargs)
[  274.455407] hibinit-agent[4484]: File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 598, in send
[  274.456594] hibinit-agent[4484]: r = adapter.send(request, **kwargs)
[  274.457076] hibinit-agent[4484]: File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 419, in send
[  274.457473] hibinit-agent[4484]: raise ConnectTimeout(e, request=request)
[  274.457606] hibinit-agent[4484]: requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/api/token (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f63c6e94190>: Failed to establish a new connection: [Errno 113] No route to host',))
```

Is this a spontaneous error? Or something related to parallel cluster?

**Comment by enrico-usai** [comment] 2020-10-22 13:23
Hi Alexis,

The reported error means that the instance is not able to retrieve internal metadata: [169.254.169.254](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html) is the link-local address.
```
[  274.457606] hibinit-agent[4484]: requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='169.254.169.254', port=80): 
Max retries exceeded with url: /latest/api/token 
(Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f63c6e94190>: 
Failed to establish a new connection: [Errno 113] No route to host',))
```

It corresponds to something like `curl http://169.254.169.254/latest/meta-data` but in your case the error is coming from cloud-init python library.

From your config I can see you're using a Custom AMI and pre/post install scripts. It could happen that some pre/post install actions break the python environment used by cloud-init or there are custom configurations in the base AMI that are breaking the environment.

From what you reported the head node is working correctly but the compute nodes are failing at startup.

* Did you try without pre/post install scripts and can you share them? 
* [Which process](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html) did you follow to create the custom ami? Are you doing any custom network setup?

To verify if there are scaling issues we need the following files:
* From Head node: `/var/log/parallelcluster/clustermgtd.log`, `/var/log/parallelcluster/slurm_resume.log`, `/var/log/parallelcluster/slurm_suspend.log`, and `/var/log/slurmctld.log`
* From Compute node:  `/var/log/parallelcluster/computemgtd.log`, and `/var/log/slurmd.log`

Thanks

**Comment by alexiswl** [comment] 2020-10-24 00:00
Hi @enrico-usai this parallel cluster was working fine for a few days successfully spawning and shutting down compute nodes as required.
I have since shut it down.  In the event that this happens again I'll retrieve these logs from the head node. 

We are using a custom AMI built through image builder that takes a pc AMI as a base and builds some conda envs on top of that along with a few standard yum installations.  We have not seen issues with this AMI before.  

Looking at those errors though, this doesn't appear to be a python issue but a network issue? 
```
Failed to establish a new connection: [Errno 113] No route to host
```

**Comment by lukeseawalker** [comment] 2020-10-29 13:24
Hi @alexiswl,
are you still experiencing this issue? If yes, can you please share the instance ID?
Are you enforcing your instance to use Instance Metadata Service Version 2 (IMDSv2) in place of IMDSv1?

**Comment by brainstorm** [comment] 2020-11-05 00:01
Hi @lukeseawalker, I'm with Alexis working on the same team.

Yesterday we noticed a similar issue with our production AWS Batch setup (unrelated with pcluster). Please can you check out [Case ID 7572098961](https://console.aws.amazon.com/support/home#/case/?displayId=7572098961&language=en) and let us know if there's some reliability internal (ongoing and increasing failure rate for the last 2-3 months) issue in ap-southeast-2 region for the instance metadata endpoints?

We submit several jobs to AWS batch but many of them are failing with messages like:

```
2020/11/04 07:08:11 E! getting instance-id from EC2 metadata fail:  RequestError: send request failed
(...)
2020/11/04 07:08:16 E! ec2metadata is not available
```

Since different agents (in our case on that issue cloudwatch-agent) rely on fetching basic information such as instance-id from the metadata endpoint, we would like to make sure that the Sydney region instance metadata service is reliable before pursuing the disabling (tedious and breakage-prone?) route since we'd have to (presumably) also check it for ecs-agent, ssm-agent et al?

**Comment by tilne** [comment] 2020-11-13 16:43
We're continuing to track an internal ticket for this issue. We'll update this issue as we learn more about the problem and any workarounds.

**Comment by lukeseawalker** [comment] 2020-12-02 09:54
Hi @brainstorm,
one root cause could be injecting huge output in the user-data, like for example the output of an unzip command. Could you please verify that?

Thanks,
L

**Comment by brainstorm** [comment] 2020-12-02 23:27
We got that solved over AWS support (and AFAIK hasn't failed since). Thanks to @reisingerf for tracking this one down to the last bit, details over here:

https://twitter.com/braincode/status/1327124842936725504

**Comment by enrico-usai** [comment] 2020-12-03 09:02
Thanks @Roman for leiting us know and for the link. 
I'm going to close this issue, feel free to open a new one if needed.

Thanks!

**Closed by enrico-usai** 2020-12-03 09:02 UTC
Labels: external, waiting customer

**Comment by enrico-usai** [comment] 2020-12-04 14:59
@alexiswl @brainstorm 
could you provide us the details of the actions you're executing in the pre/post-install actions, if any?

This info could be helpful to try to reproduce the issue and verify if we can do something to improve the user's experience.
Thanks

**Comment by brainstorm** [comment] 2020-12-05 07:24
@enrico-usai IIRC, this was the culprit: https://github.com/umccr/infrastructure/commit/2df50d503532eee76675bb34972836ed817f35a3

Hope that helps!
