### ISSUE TITLE
Support for copying base AMI (Centos7) to china region

### ISSUE THREAD

**Issue by SivaKanishka** [aws/aws-parallelcluster#2192] opened 2020-11-02 10:04 UTC
Hello,

I found that there is no AWS Parallelcluster compatible base AMI in this [repo](https://github.com/aws/aws-parallelcluster/blob/v2.9.1/amis.txt). I have a custom AMI for parallelcluster built in a different region. Is it possible to copy my custom AMI to china region?

**Comment by lukeseawalker** [comment] 2020-11-02 11:38
Hello,
at the moment you can follow [this guide](http://d1.awsstatic.com/whitepapers/migrating-linux-and-windows-AMIs-from-global-regions-to-china-regions.pdf) to migrate AMI from global regions to China regions.
Support for CentOS AMI in China regions is tracked by https://github.com/aws/aws-parallelcluster/issues/1491

**Comment by SivaKanishka** [comment] 2020-11-04 09:39
Thanks @lukeseawalker 

I followed the documentation you shared. Surprisingly, transfer time between global region instance and China region instance is very slow (15Kbs). It turned out to be not feasible for my case.

I saw that there is an official Centos7 AMI in China region. Are there any plans to release an Parallelcluster compatible AMI in future?

**Comment by nstornetta** [comment] 2020-11-05 15:50
Adding support for CentOS in China is part of our product roadmap. Unfortunately, we do not have an ETA for this item. While there are some CentOS AMIs available in China, these are not compatible for use with ParallelCluster due to limitations on their reuse and republication. We are working with the CentOS community to make compatible AMIs available in China and will then be able to include support for them inside ParallelCluster.

**Comment by demartinofra** [comment] 2020-11-06 09:14
I'm going to resolve this as a duplicate of https://github.com/aws/aws-parallelcluster/issues/1491

**Closed by demartinofra** 2020-11-06 09:14 UTC
