### ISSUE TITLE
disable_hyperthreading throws an error if the Master instance does not support it

### ISSUE THREAD

**Issue by RickoLacharity** [aws/aws-parallelcluster#1507] opened 2019-11-29 21:35 UTC
`ERROR: The t2.micro instance type does not support specifying disable_hyperthreading.`

For users who only use the master instance for the scheduler and maybe a license server, it is fine (possibly preferred) to leave hyperthreading enabled on the master node. For users that use the master node for pre and post-processing of jobs, they may want to be able to disable hyperthreading on the master node. 

disable_hyperthreading could accept the options: [false, true, compute].

For the time being, I will have to switch to the c5.large for my master's instance. This makes the cost 8x more expensive on an instance that has to be running all the time.

**Comment by demartinofra** [comment] 2019-12-02 09:24
Hi @RickoLacharity 

this sounds like a pretty legitimate request. Marking it as an enhancement.

**Comment by sean-smith** [comment] 2019-12-04 17:08
@RickoLacharity You can use `t3.*` instances w/ `disable_hyperthreading`. See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-optimize-cpu.html#cpu-options-supported-instances-values for a complete list of supported instances.

**Comment by ganderaj** [comment] 2020-01-31 12:32
@sean-smith 

Why can't we have a cluster where hyperthreading is disabled on compute nodes but not on the master? Why should it be entire cluster as a whole? Are there any technical challenges from the AWS Side?

I am assuming future release of Parallel Cluster upon requesting for features might come up with a config parameter which will allow the users to toggle between compute/cluster at the time of choosing to disable_hyperthreading. It's pretty much similar to using the config parameter "placement" if you would like to opt for "placement_group".

**Comment by ddeidda** [comment] 2020-02-03 10:12
Marked as duplicate of https://github.com/aws/aws-parallelcluster/issues/1627 since it refers to the same feature request.

**Closed by ddeidda** 2020-02-03 10:12 UTC
Labels: duplicate, enhancement
