### ISSUE TITLE
Parallel Cluster launch fails with EFA enabled

### ISSUE THREAD

**Issue by gallanik-zs** [aws/aws-parallelcluster#3590] opened 2021-12-10 11:18 UTC
- AWS ParallelCluster version [e.g. 2.9.0]: 3.0.2
 - Full cluster configuration without any credentials or personal data: 
[hpc-with-efa.yaml.txt](https://github.com/aws/aws-parallelcluster/files/7691618/hpc-with-efa.yaml.txt)
 - Cluster name: hpc-with-efa

**Bug description and how to reproduce:**
I am trying to create a Parallel cluster with EFA enabled, and have created a security group as instructed here [AWS Documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html). But while launching, it fails with the following error -

```
{
      "level": "ERROR",
      "type": "EfaSecurityGroupValidator",
      "message": "An EFA requires a security group that allows all inbound and outbound traffic to and from the security group itself. See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-security"
}
```

The security group I am using is configured correctly as shown here - 
![sg-outbound](https://user-images.githubusercontent.com/95228016/145565944-89e614b3-6330-4a73-b757-35acb1dfca4b.jpg)
![sg-inbound](https://user-images.githubusercontent.com/95228016/145565951-8682835f-9a5e-4559-a021-979af1d41765.jpg)

I was able to launch a standalone EC2 instance with EFA enabled and the same security group without any issues.

**Comment by hanwen-pcluste** [comment] 2021-12-13 19:28
Hello Gallanik,

Your security groups look good to me. You can use `--suppress-validators type:EfaSecurityGroupValidator` in the [`create-cluster` command](https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.create-cluster-v3.html) to suppress the error and continue the cluster creation.

Moreover, I couldn't reproduce your issue. To help us understand the issue better, could you run the following python code and show us the printed content?
```
import boto3
sg = boto3.client("ec2").describe_security_groups(GroupIds=["sg-09f28e9fbfd632c3b"]).get("SecurityGroups")[0]
print(sg)
```

Thank you,
Hanwen

**Comment by gallanik-zs** [comment] 2021-12-14 07:37
Here is the pretty output (with masked sensitive values):

```
{
  "Description": "Allow access to compute nodes",
  "GroupName": "ComputeSecurityGroup-XHCTUIZWJFML",
  "IpPermissions": [
    {
      "IpProtocol": "-1",
      "IpRanges": [],
      "Ipv6Ranges": [],
      "PrefixListIds": [],
      "UserIdGroupPairs": [
        {
          "GroupId": "sg-0521b20e857e3ee85",
          "UserId": "20781xxxxx05"
        },
        {
          "GroupId": "sg-09f28e9fbfd632c3b",
          "UserId": "20781xxxxx05"
        }
      ]
    }
  ],
  "OwnerId": "20781xxxxx05",
  "GroupId": "sg-09f28e9fbfd632c3b",
  "IpPermissionsEgress": [
    {
      "IpProtocol": "-1",
      "IpRanges": [
        {
          "CidrIp": "0.0.0.0/0"
        }
      ],
      "Ipv6Ranges": [],
      "PrefixListIds": [],
      "UserIdGroupPairs": [
        {
          "GroupId": "sg-09f28e9fbfd632c3b",
          "UserId": "20781xxxxx05"
        }
      ]
    }
  ]
  "VpcId": "vpc-003xxxxxxxxxxxxxx"
}
```

**Comment by hanwen-pcluste** [comment] 2021-12-15 15:28
Hello Gallanik,

Thank you for letting us know the bug. I've fix the bug. The fix will be included in the next ParallelCluster 3 release.
For now, You can use `--suppress-validators type:EfaSecurityGroupValidator` in the [`create-cluster` command](https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.create-cluster-v3.html) to suppress the error and continue the cluster creation.

Thank you

**Comment by enrico-usai** [comment] 2022-02-11 09:45
ParallelCluster 3.1.1, including this fix, has been released: https://github.com/aws/aws-parallelcluster/releases/tag/v3.1.1

**Closed as completed by enrico-usai** 2022-02-11 09:45 UTC
Labels: Bug, 3.x
