### ISSUE TITLE
ERROR when deleting a cluster

### ISSUE THREAD

**Issue by JosephDVL** [aws/aws-parallelcluster#1498] opened 2019-11-27 03:10 UTC
**Environment:**
 - AWS ParallelCluster aws-parallelcluster-2.5.0
 - OS: alinux
 - Scheduler: SGE
 - Master instance type: t3.large
 - Compute instance type: m3.medium

**Bug description and how to reproduce:**
When deleting a cluster using:

`pcluster delete ${cluster-name}`

the following error is returned:

    Deleting: nuevo-campaign17
    Status: DynamoDBTable - DELETE_COMPLETE                                         ERROR: Stack with id parallelcluster-nuevo-campaign17 does not exist

with the spacing as shown in the block above.

**Comment by enrico-usai** [comment] 2019-11-27 08:19
Hi @JosephDVL ,
the patch for this issue has been already merged in the develop branch. It will be part of the next release.

The pcluster delete command is showing a wrong message, but all the cluster resources are correctly deleted, thank you for reporting this.

Patch: https://github.com/aws/aws-parallelcluster/pull/1474 
Duplicate of: https://github.com/aws/aws-parallelcluster/issues/1485

**Closed** 2019-11-27 08:19 UTC
