### ISSUE TITLE
pcluster with sge does not fully respect "-tc" flag.

### ISSUE THREAD

**Issue by amniskin** [aws/aws-parallelcluster#1760] opened 2020-05-05 18:33 UTC
**Environment:**
 - AWS ParallelCluster-2.6.0
 - Configuration file
```yaml[global]
cluster_template = default
update_check = true
sanity_check = true

[aws]
aws_region_name = xxxxxxxxxxxx

[cluster default]
base_os = ubuntu1804
cluster_type = spot
compute_instance_type = m4.4xlarge
compute_root_volume_size = 100
custom_ami = ami-xxxxxxxxxxxxxxxxxx
cw_log_settings = default-cw
ebs_settings = default-ebs
ec2_iam_role = xxxxxxxxxxxxxxxxxx
efs_settings = default-efs
encrypted_ephemeral = false
ephemeral_dir = /scratch
extra_json = { "cluster" : { "cfn_scheduler_slots" : "1", "ganglia_enabled": "yes" } }
initial_queue_size = 2
key_name = xxxxxxxxxxxxxx
maintain_initial_size = false
master_instance_type = t2.xlarge
master_root_volume_size = 100
max_queue_size = 200
placement = compute
placement_group = DYNAMIC
scaling_settings = default-scaling
scheduler = sge
shared_dir = /shared-master
tags = {"user" : "meeeee", "project" : "Research", "Name": "cluster-name"}
vpc_settings = default-vpc


[cw_log default-cw]
enable = true
retention_days = 120

[ebs default-ebs]
shared_dir = /shared-ebs
volume_type = gp2
volume_size = 100

[efs default-efs]
shared_dir = /shared-efs
efs_fs_id = fs-xxxxxxxxxx

[scaling default-scaling]
scaledown_idletime = 10

[vpc default-vpc]
vpc_id = vpc-xxxxxxxxxxxx
vpc_security_group_id = sg-xxxxxxxxxx
master_subnet_id = subnet-xxxxxxxxx
use_public_ips = true
```

**Bug description and how to reproduce:**
When a script is submitted as an array job but limiting concurrency via the "-tc" flag it spins up enough nodes to run each job, but runs the jobs with the appropriate concurrency.

E.g.
```bash
#!/bin/bash
# contents of remote.sh
echo 'this is a test'
```

```bash
qsub -N test -notify -t 1-100 -tc 5 remote.sh
```
will spin up 100 nodes then run 5 jobs at a time, leaving 95 nodes alive and waiting.

**Additional context:**
Nothing that I can think of.

**Comment by demartinofra** [comment] 2020-05-27 12:52
Sorry for the late reply. I'm going to try to reproduce this issue today and get back with an update.

**Comment by demartinofra** [comment] 2020-05-27 13:58
Ok so what's happening is that the current ParallelCluster scaling logic does not support the `-tc` option which means it tries to launch a number of nodes required to satisfy the entire array job. However SGE is not going to run more than 5 jobs at the time because of the specified constraint.

I'm going to mark this as an enhancement request.

**Comment by nstornetta** [comment] 2020-06-08 22:24
Because we have announced that we will be deprecating support for SGE in the near-future (see: https://github.com/aws/aws-parallelcluster/wiki/Deprecation-of-SGE-and-Torque-in-ParallelCluster), we will not be performing additional enhancements specific to SGE.

I am going to close this issue. If you would like to request a similar enhancement for one of our other supported schedulers (Slurm or AWS Batch), please feel free to create a new issue.

**Closed by nstornetta** 2020-06-08 22:24 UTC
Labels: enhancement
