### ISSUE TITLE
Error in pcluster 2.8.1 Master node using pdsh

### ISSUE THREAD

**Issue by vbosquier** [aws/aws-parallelcluster#2416] opened 2021-02-03 09:35 UTC
Hi PC Team!

I have deployed pdsh on the master node of a cluster launched using ParallelCluster 2.8.1 on Centos 7.

I've got the following error message when executing pdsh:
```
$ pdsh -w ip-10-0-208-156,ip-10-0-248-39,ip-10-0-254-161 hostname
ip-10-0-248-39: /bin/ssh_target_checker.sh: line 27: syntax error near unexpected token `<'
ip-10-0-248-39: /bin/ssh_target_checker.sh: line 27: `    if ! mapfile -t vpc_cidr_list < <(curl --retry 3 --retry-delay 0 --silent --fail "${vpc_cidr_uri}"); then'
ip-10-0-254-161: /bin/ssh_target_checker.sh: line 27: syntax error near unexpected token `<'
ip-10-0-254-161: /bin/ssh_target_checker.sh: line 27: `    if ! mapfile -t vpc_cidr_list < <(curl --retry 3 --retry-delay 0 --silent --fail "${vpc_cidr_uri}"); then'
ip-10-0-208-156: /bin/ssh_target_checker.sh: line 27: syntax error near unexpected token `<'
ip-10-0-208-156: /bin/ssh_target_checker.sh: line 27: `    if ! mapfile -t vpc_cidr_list < <(curl --retry 3 --retry-delay 0 --silent --fail "${vpc_cidr_uri}"); then'
ip-10-0-248-39: ip-10-0-248-39
ip-10-0-254-161: ip-10-0-254-161
ip-10-0-208-156: ip-10-0-208-156
```
I could see in a PC cookbook that ssh configuration in PC clusters references "ssh_target_checker.sh", as you can see here:
https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/attributes/default.rb

Please can you help me understand what's going on?

Best regards,
Vincent.

**Comment by rexcsn** [comment] 2021-02-05 18:46
Hi @vbosquier,

`ssh_target_checker.sh` was written to be used by ssh. There is no issue when the script is used by ssh, but looks like the syntax of file is not compatible with some commands that depends on ssh, such as pdsh.
We can fix the syntax error for pdsh easily, PR here: https://github.com/aws/aws-parallelcluster-cookbook/pull/864

Please let us know if you have any question. Thanks!

**Comment by rexcsn** [comment] 2021-03-03 19:24
Hi, I assume the issue is resolved, closing the issue now.
Please let us know if you have any question. Thanks!

**Closed by rexcsn** 2021-03-03 19:24 UTC
Labels: waiting customer
