### ISSUE TITLE
Cannot attaches existing FSx for Lustre in China Region

### ISSUE THREAD

**Issue by hy714335634** [aws/aws-parallelcluster#2181] opened 2020-10-29 10:16 UTC
**Required Info:**
 - AWS ParallelCluster version [e.g. 2.9.0]:2.8.1

**Bug description and how to reproduce:**
I want to attaches an existing Amazon FSx for Lustre file system in new cluster, the templete like this:
```shell
[fsx fsxshared]
shared_dir = /fsx
fsx_fs_id = fs-xxxx
```
MasterServerWaitCondition will be 'CREATE_FAILED', and I found the mount command like this in ***cfn-init-cmd.log***
```shell
2020-10-29 09:54:39,002 P1460 [INFO]    ---- End output of ["mount", "-t", "lustre", "-o", "defaults,_netdev,flock,user_xattr,noatime,noauto,x-systemd.automount", "fs-xxxx.fsx.cn-northwest-1.amazonaws.com.cn@tcp:/7t4c7bmv", "/fsx"] ----
2020-10-29 09:54:39,003 P1460 [INFO]    Ran ["mount", "-t", "lustre", "-o", "defaults,_netdev,flock,user_xattr,noatime,noauto,x-systemd.automount", "fs-xxxx.fsx.cn-northwest-1.amazonaws.com.cn@tcp:/7t4c7bmv", "/fsx"] returned 22
```
It's a wrong domain in china region***(*.amazonaws.com.cn -> amazonaws.com)***, here is right command, and it's work:
```shell
mount -t lustre -o defaults,_netdev,flock,user_xattr,noatime,noauto,x-systemd.automount fs-xxxx.fsx.cn-northwest-1.amazonaws.com@tcp:/7t4c7bmv /fsx 
```

**Comment by lukeseawalker** [comment] 2020-10-29 14:51
Hi @hy714335634,
thanks for reporting this. We are aware of the problem and investigating.

**Comment by demartinofra** [comment] 2020-11-04 09:38
The issue is due to a misalignment between the domain version expected by ParallelCluster (amazonaws.com.cn) and the domain exposed by FSX  in China regions (amazonaws.com). While support for amazonaws.com.cn domain is being added, a fix has been merged to work with the current domain and is going to be released with the upcoming version of ParallelCluster. 

The workaround until the new PCluster version containing the fix will be released or until the support for the amazonaws.com.cn is available is to create a custom cookbook containing the changes reported [here](https://github.com/aws/aws-parallelcluster-cookbook/pull/792/files) and use this custom cookbook as value for custom_chef_cookbook variable, following procedure described [here](https://docs.aws.amazon.com/parallelcluster/latest/ug/custom_cookbook.html).

**Comment by enrico-usai** [comment] 2020-11-18 17:23
[2.10.0](https://github.com/aws/aws-parallelcluster/releases/tag/v2.10.0) release is out. Thanks for reporting this.

**Closed by enrico-usai** 2020-11-18 17:23 UTC
Labels: bug, pending release
