### ISSUE TITLE
pcluster stops with "Rate exceeded" and no further output but cluster is actually created

### ISSUE THREAD

**Issue by PhilipMorrisJones** [aws/aws-parallelcluster#1493] opened 2019-11-26 09:17 UTC
**Environment:**
 - aws-parallelcluster-2.4.1
 - OS: centos7
 - Scheduler: SGE
 - Master instance type: c5.xlarge
 - Compute instance type: c5n.18xlarge

**Bug description and how to reproduce:**

Build a cluster with attached config.

[config_110.txt](https://github.com/aws/aws-parallelcluster/files/3890952/config_110.txt)

The output is

```
$ pcluster create -c config_110 pmj-tue-110
Beginning cluster creation for cluster: pmj-tue-110
warning: There is a newer version 2.5.0 of AWS ParallelCluster available.
Creating stack named: parallelcluster-pmj-tue-110
Status: ComputeFleet - CREATE_IN_PROGRESS                                       Rate exceeded
```
I can, however, get the cluster status

```
$ pcluster status pmj-tue-110
warning: There is a newer version 2.5.0 of AWS ParallelCluster available.
Status: CREATE_COMPLETE
MasterServer: RUNNING
MasterPublicIP: 3.224.134.177
ClusterUser: centos
MasterPrivateIP: 10.0.0.204
```

and ssh to it and I have 110 nodes (3,960 cores without hyper-threading)

```
metis<56>ssh -i pmj_private_key.pem centos@3.224.134.177
Last login: Tue Nov 26 09:07:16 2019 from 81.134.157.126
[centos@ip-10-0-0-204 ~]$ qstat -g c
CLUSTER QUEUE                   CQLOAD   USED    RES  AVAIL  TOTAL aoACDS  cdsuE
--------------------------------------------------------------------------------
all.q                             0.00      0      0   3960   3960      0      0
```

**Comment by demartinofra** [comment] 2019-11-26 12:20
Hi,

unfortunately the Rate exceeded error is coming from CloudFormation API and it is due to some API throttling caused by the fact that 110 nodes are being launched in the cluster and each of them performs a call to CloudFormation. As you noticed the creation of the cluster should not be affected.

In order to improve the customer experience we should better handle such errors inside our CLI code.

**Comment by PhilipMorrisJones** [comment] 2019-11-26 17:45
Hi, yes, agree. The cluster is created but no message to say so and with 110 instances it is easily possible to rack up a big bill and not realise. Any helpful messages would be appreciated.

**Comment by demartinofra** [comment] 2020-01-24 13:58
This issue is being addressed as part of https://github.com/aws/aws-parallelcluster/pull/1596 and the fix will be released as part of the next version of ParallelCluster

**Comment by lukeseawalker** [comment] 2020-02-26 21:33
AWS ParallelCluster 2.6.0 with the fix mentioned above has been released

**Closed by lukeseawalker** 2020-02-26 21:33 UTC
Labels: bug, enhancement, pending release
