### ISSUE TITLE
Build image hangs on interactive prompt

### ISSUE THREAD

**Issue by popgendad** [aws/aws-parallelcluster#4058] opened 2022-05-24 16:19 UTC
AWS ParallelCluster version: 3.1.4

**Bug description and how to reproduce:**
Build image hangs on ubuntu because install of `openssh-server`, debconf brings up interactive prompt. It happens when `UpdateOsPackages: True` or `UpdateOsPackages: False`

Build command:
```
pcluster build-image --image-id XXX --image-configuration XXX.yaml --region XXX
```

Build config file:
```
Region: XXX
Build:
  InstanceType: m6g.large
  SubnetId: XXX
  ParentImage: ami-XXX
  Iam:
    InstanceRole: arn:aws:iam::XXXX
  Components:
    - Type: arn
      Value: arn:aws:imagebuilder:XXX
  UpdateOsPackages:
    Enabled: False
  SecurityGroupIds:
    - sg-XXX
Image:
  Name: cluster-ami
  RootVolume:
    Size: 35
    Encrypted: False
```

Image build log where process hangs:
```
    {
      "message": "Stdout: Setting up openssh-server (1:8.2p1-4ubuntu0.5) ...",
      "timestamp": "2022-05-23T17:16:52.804Z"
    },
    {
      "message": "Stdout: debconf: unable to initialize frontend: Dialog",
      "timestamp": "2022-05-23T17:16:53.076Z"
    },
    {
      "message": "Stdout: debconf: (TERM is not set, so the dialog frontend is not usable.)",
      "timestamp": "2022-05-23T17:16:53.076Z"
    },
    {
      "message": "Stdout: debconf: falling back to frontend: Readline",
      "timestamp": "2022-05-23T17:16:53.076Z"
    },
    {
      "message": "Stdout: Configuring openssh-server",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout: --------------------------",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout: ",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout: A new version (/tmp/filefswXVy) of configuration file /etc/ssh/sshd_config is ",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout: available, but the version installed currently has been locally modified.",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout: ",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout:   1. install the package maintainer's version",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout:   2. keep the local version currently installed",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout:   3. show the differences between the versions",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout:   4. show a side-by-side difference between the versions",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout:   5. show a 3-way difference between available versions",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout:   6. do a 3-way merge between available versions",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout:   7. start a new shell to examine the situation",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout: ",
      "timestamp": "2022-05-23T17:16:53.180Z"
    }
```

**Comment by enrico-usai** [comment] 2022-05-25 10:40
Hi @popgendad 

the AMI you're using as `ParentImage` is a public one?  If so, can you share the AMI id? In this way we can try to reproduce.

If the `ParentImage` is not public could you please execute the following commands on it:
```
apt-get -V -s upgrade openssh-server
```
```
apt show openssh-server -a
```
Thanks

**Comment by popgendad** [comment] 2022-05-25 15:33
Hi @enrico-usai 
Thanks for your reply, I am using the parallelcluster 3.1.4 ubuntu 20.04 arm64 base image
```
amiID: ami-05e7fea4bacc5792d
name: aws-parallelcluster-3.1.4-ubuntu-2004-lts-hvm-arm64-202205121006 2022-05-12T10-09-44.849Z
```

**Comment by enrico-usai** [comment] 2022-05-30 09:30
Hi @popgendad 

Thanks for the info, anyway you shouldn't use a ParallelCluster AMI as `ParentImage`.

There are [two ways](https://docs.aws.amazon.com/parallelcluster/latest/ug/building-custom-ami-v3.html) to create Custom AMIs for ParallelCluster: 
1. [Build a Custom AWS ParallelCluster AMI](https://docs.aws.amazon.com/parallelcluster/latest/ug/building-custom-ami-v3.html#build-a-custom-aws-parallelcluster-ami)
2. [Modify an AWS ParallelCluster AMI](https://docs.aws.amazon.com/parallelcluster/latest/ug/building-custom-ami-v3.html#modify-an-aws-parallelcluster-ami)

If you're using the 1st approach (`pcluster build-image`) you should use your personal AMI as ParentImage, not a ParallelCluster AMI, because the scope of the `build-image` process is to add ParallelCluster stuff on top of your AMI (with just your your software).

If you're using the 2nd approach, and you created a custom AMI starting from `ami-05e7fea4bacc5792d` and adding your software on top of it, you don't need to execute the `build-image` command, you can simply add it as `CustomAmi` in the cluster configuration.

Then let me also add that if your customization is a simple and fast one, the recommended approach is to use [Custom Bootstrap Actions](https://docs.aws.amazon.com/parallelcluster/latest/ug/custom-bootstrap-actions-v3.html) rather than building a custom AMI.

Could you please clarify which process are you following? 
Are you passing the `ami-05e7fea4bacc5792d` as `ParentImage`?

Enrico

**Comment by popgendad** [comment] 2022-05-30 14:32
Hi @enrico-usai ok my bad, I had been using the parallelcluster AMIs with EC2-Image-Builder, so I see now how pcluster build-image will just re-install and re-configure the packages.

**Comment by enrico-usai** [comment] 2022-05-30 14:51
Thanks for the update. Resolving the ticket. 
Enrico

**Closed as completed by enrico-usai** 2022-05-30 14:51 UTC
Labels: 3.x
