### ISSUE TITLE
ERROR: The configuration parameter 'disable_hyperthreading' has an invalid value 'True'

### ISSUE THREAD

**Issue by PhilipMorrisJones** [aws/aws-parallelcluster#1540] opened 2019-12-10 10:55 UTC
**Environment:**
 - AWS ParallelCluster 2.5.0
 - OS: centos
 - Scheduler: SGE

**Bug description and how to reproduce:**

```
$ pcluster create -c config_250_noHT pmj-tue-test2
Beginning cluster creation for cluster: pmj-tue-test2
ERROR: The configuration parameter 'disable_hyperthreading' has an invalid value 'True'
cfn_scheduler_slots cannot be set in addition to disable_hyperthreading = true
Creating stack named: parallelcluster-pmj-tue-test2
Status: parallelcluster-pmj-tue-test2 - CREATE_COMPLETE                         
MasterPublicIP: 3.213.63.193
ClusterUser: centos
MasterPrivateIP: 10.0.0.114
```

I have a line in my config to turn hyperthreading off and I get an error message. The error says "true" but my config says "true"

It still seems to work, so the default config has c5.xlarge with 4 CPUs and all online

```
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
```

and with the flag, I get just 2 online

```
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
```

```
[cluster default]
vpc_settings = public
fsx_settings = fsxshared
base_os = centos7
enable_efa = compute
scaling_settings = custom
key_name = pmj_private_key
compute_instance_type = c5n.18xlarge
master_instance_type = c5.xlarge
extra_json = { "cluster" : { "cfn_scheduler_slots" : "cores" } }
s3_read_write_resource = *
cluster_type = ondemand
placement_group = DYNAMIC
placement = compute
max_queue_size = 30
initial_queue_size = 0
maintain_initial_size = true
disable_hyperthreading = true
```

**Comment by enrico-usai** [comment] 2019-12-10 11:25
Hi @PhilipMorrisJones,
the problem is explained in the second row of the error message:
`cfn_scheduler_slots cannot be set in addition to disable_hyperthreading = true`

You should remove the `extra_json` parameter or turn off `disable_hyperthreading`, by setting the parameter to `false`.

**Comment by PhilipMorrisJones** [comment] 2019-12-10 12:02
OK, the erorr message is confusing. It first says my disable_hyperthreading has an invalid value. If the extra_json is the issue it should start with that as a message.

**Comment by enrico-usai** [comment] 2019-12-10 12:04
Yes, I agree the first row of the message is misleading.
Thank you for the feedback.

**Comment by PhilipMorrisJones** [comment] 2019-12-10 13:15
I confirm that removing the `extra_json` line gets me to what I want. Do you want me to close this out?

**Comment by enrico-usai** [comment] 2019-12-10 17:05
I created a patch to improve the error message: https://github.com/aws/aws-parallelcluster/pull/1543

**Comment by demartinofra** [comment] 2019-12-13 17:02
Fixed in https://github.com/aws/aws-parallelcluster/releases/tag/v2.5.1

**Closed by demartinofra** 2019-12-13 17:02 UTC
Labels: pending release
