### ISSUE TITLE
Warning when accessing pre and post script

### ISSUE THREAD

**Issue by medcelerate** [aws/aws-parallelcluster#1725] opened 2020-04-09 19:56 UTC
**Environment:**
 - AWS ParallelCluster 2.6.0

```
[aws]
aws_region_name = us-east-1

[global]
cluster_template = pcprod
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[cluster pcprod]

key_name = s4-sinaia-valinor-nphi
base_os = alinux2
cluster_type = ondemand
scheduler = slurm

master_instance_type = m4.4xlarge
compute_instance_type = c5.12xlarge
compute_root_volume_size = 500
master_root_volume_size = 800

initial_queue_size = 1
max_queue_size = 800
maintain_initial_size = false

s3_read_resource = arn:aws:s3:::s4-sinaia-valinor-nphi/*
s3_read_write_resource = arn:aws:s3:::s4-sinaia-valinor-nphi/*

tags = {"RunSchedule": "24x7", "PC": "PCPROD"}

extra_json = { "cluster" : { "ganglia_enabled" : "yes" } }

fsx_settings = performancefs
efs_settings = generalfs
scaling_settings = sc
cw_log_settings = pcprodlog

post_install = https://gitlab.com/iidsgt/parallel-cluster/-/raw/master/ProdPostInstall.py
pre_install = https://gitlab.com/iidsgt/parallel-cluster/-/raw/master/ProdPreInstall.py

post_install_args = "{cromwell_db_user} {cromwell_db_password} {S3_Key} {S3_Secret}"

vpc_settings = pcluster

[cw_log pcprodlog]
enable = true
retention_days = 14

[efs generalfs]
shared_dir = /efs
performance_mode = generalPurpose

[fsx performancefs]
shared_dir = /fsx
storage_capacity = 9600
#imported_file_chunk_size = 1024
deployment_type = SCRATCH_2
#export_path = s3://parallelcluster/fsx
#import_path = s3://parallelcluster
weekly_maintenance_start_time = 5:00:00


[scaling sc]
scaledown_idletime = 60

[vpc pcluster]
vpc_id = vpc-06340ae1a9fc97bfd
master_subnet_id = subnet-04b5ef81c6a93137b
compute_subnet_id = subnet-023bbab22f5917c5a
use_public_ips = false
```

**Bug description and how to reproduce:**
Run pcluster create with the above config file and it gives these errors. I was previously able to run it without issue.
```
WARNING: The configuration parameter 'pre_install' generated the following warnings:
https://gitlab.com/iidsgt/parallel-cluster/-/raw/fb882d4fbe2cf2773c246636e0e6ba55934ef0dc/ProdPreInstall.py 403 Forbidden
WARNING: The configuration parameter 'post_install' generated the following warnings:
https://gitlab.com/iidsgt/parallel-cluster/-/raw/fb882d4fbe2cf2773c246636e0e6ba55934ef0dc/ProdPostInstall.py 403 Forbidden
```

**Comment by enrico-usai** [comment] 2020-04-10 14:25
Hi @medcelerate 
this warning appears because we added an URL validator for the pre/post install script parameters.

This validation is executed at creation time, to check if the URL used for the script is accessible or not.

In your case the URL is not accessible by the role executing the CLI, but as you noted it is a WARNING and not an ERROR because the file could be not accessible by the CLI but it could be from inside the instances.

If it is by design and the script are accessible from inside the instances feel free to go ahead and ignore the warnings.

Let us know if it helps.

**Comment by medcelerate** [comment] 2020-04-10 19:18
The issue seems to be related to gitlab thinking the repeated requests for the file are a botnet. Moving the files to a different storage location solved the problem.

**Comment by enrico-usai** [comment] 2020-04-13 11:41
Thanks for sharing your solution.
I'm going to close this issue. 
Feel free to open a new one in case of any question.

**Closed by enrico-usai** 2020-04-13 11:41 UTC

**Comment by medcelerate** [comment] 2020-04-13 13:32
@enrico-usai So this is interesting, this url worked fine when we spun up our previous cluster using 2.6, it is accessible from my computer however on aws it throws a 403 error. This may be an issue on gitlab
