### ISSUE TITLE
Feature Request: Allow tags to be configured  in the SharedStorage.EbsSettings configuration 

### ISSUE THREAD

**Issue by snemir2** [aws/aws-parallelcluster#6227] opened 2024-04-27 18:31 UTC
If you have an active AWS support contract, please open a case with AWS Premium Support team using the below documentation to report the issue:
https://docs.aws.amazon.com/awssupport/latest/user/case-management.html

Before submitting a new issue, please search through open [GitHub Issues](https://github.com/aws/aws-parallelcluster/issues) and check out the [troubleshooting documentation](https://docs.aws.amazon.com/parallelcluster/latest/ug/troubleshooting-v3.html).

Please make sure to add the following data in order to facilitate the root cause detection.

**Required Info:**
 - AWS ParallelCluster version:3.9.1
 -
**Bug description and how to reproduce:**
For shared ebs volume, it would be very useful if we could tag it from the cluster configuration. 
For example, it would work well for us if we could create a volume with a cluster and set the DeletionPolicy to Delete, but we would want to tag this volume for backup service backup.

**Comment by enrico-usai** [comment] 2024-05-23 16:54
Still valid but closing as duplicate of: https://github.com/aws/aws-parallelcluster/issues/5126

**Closed as completed by enrico-usai** 2024-05-23 16:54 UTC
Labels: 3.x
