### ISSUE TITLE
Launch a cluster with FSx for Lustre storage request failed

### ISSUE THREAD

**Issue by rangsimanketkaew** [aws/aws-parallelcluster#1722] opened 2020-04-08 06:48 UTC
**Environment:**
 - AWS ParallelCluster v2.6.0
 - Configuration file

```
[global]
cluster_template = default
update_check = true
sanity_check = true

[aws]
aws_region_name = us-east-1

[cluster default]
key_name = BATMAN
base_os = ubuntu1804
custom_ami = ami-xxxxxxxxxxxxxxxxx
master_instance_type = c5.xlarge
compute_instance_type = g4dn.8xlarge
master_root_volume_size = 100
compute_root_volume_size = 30
initial_queue_size = 1
max_queue_size = 10
max_vcpus = 360
maintain_initial_size = true
scheduler = slurm
cluster_type = spot
placement = cluster
placement_group = DYNAMIC
fsx_settings = fs
vpc_settings = public
scaling_settings = custom

[fsx fs]
shared_dir = /fsx
storage_capacity = 2400

[vpc public]
vpc_id = vpc-xxxxxxxxxxxxxxxxxxxx
master_subnet_id = subnet-xxxxxxxxxxxxxxxxxxxxx

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[scaling custom]
scaledown_idletime = 10
```

Pcluster create had taken around 10-15 minutes and it did eventually fail at AWSCloudFormation process with the following error:

```
Status: parallelcluster-test-cluster-fsx - CREATE_FAILED
Cluster creation failed.  Failed events:
  - AWS::CloudFormation::Stack parallelcluster-test-gmx-fsx-nutt-norollback The following resource(s) failed to create: [MasterServerWaitCondition, ComputeFleet].
  - AWS::AutoScaling::AutoScalingGroup ComputeFleet Resource creation cancelled
  - AWS::CloudFormation::WaitCondition MasterServerWaitCondition Received FAILURE signal with UniqueId i-09e2969b3fd86a7a1
```

**Additional context:**
 - Then I re-execute `create` action using `--norollback` option and [here are three important log files from /var/log/ folder on the master node](https://drive.google.com/drive/folders/151C4PHc7Ni3fT_utYeIirwBr5RMuEASd?usp=sharing) which might help you for diagnosis.

Can anyone here help and guide me how to handle this problem?

Thank you very much

Rangsiman

**Comment by demartinofra** [comment] 2020-04-14 08:28
Hi Rangsiman,

I tried to reproduce your issue but I wasn't able to. The only difference with my cluster configuration is the fact that I'm not using a `custom_ami`.

I also looked at your logs and from the `cfn-init.log` file I can see that the mountpoint we use for fsx is empty for some reason and this is causing the failure.

Can you try to ssh into the Master node of the cluster and run the following command:
```
sudo /usr/local/pyenv/versions/cookbook_virtualenv/bin/aws fsx --region us-east-1 describe-file-systems --file-system-ids fs-0dd04423a9efca0b4 --query 'FileSystems[0].LustreConfiguration.MountName' --output text
```
This is the command ParallelCluster uses to retrieve the FSx mountpoint. My guess is that for some reason this command is failing and we get an empty mountpoint. Unfortunately I cannot deduce this from the logs and that is why I'm asking you to run the command above.

Also how are you building your custom_ami?

Some additional notes on your config (unrelated to the issue):
- `max_vcpus` only takes effect when `awsbatch` is the scheduler
- I'd recommend to replace `placement = cluster` with `placement = compute` when using a master instance type that differs from the compute instance type. This reduces the chances of hitting capacity provisioning issues due to the impossibilities to place heterogeneous instance types in the same placement group.

**Comment by rangsimanketkaew** [comment] 2020-04-14 09:19
Hi demartinofra,

Thank for your help! I built my custom_ami as follows:
1. Launch a standalone Ubuntu instance using an AMI id given in this [amis.txt](https://github.com/aws/aws-parallelcluster/blob/develop/amis.txt) for US Virginia region.
2. I updated and upgraded the packages and installed other software
3. Created a new AMI from that pre-configured Ubuntu instance
4. Launched my parallel cluster using this custom_ami

Now I am trying to launch the cluster again and will then run the command you suggested.
```
sudo /usr/local/pyenv/versions/cookbook_virtualenv/bin/aws fsx --region us-east-1 describe-file-systems --file-system-ids fs-0dd04423a9efca0b4 --query 'FileSystems[0].LustreConfiguration.MountName' --output text
```

Rangsiman

**Comment by rangsimanketkaew** [comment] 2020-04-14 10:25
I already ran the command
```
sudo /usr/local/pyenv/versions/cookbook_virtualenv/bin/aws fsx --region us-east-1 describe-file-systems --file-system-ids fs-0fdc3163ca0708876 --query 'FileSystems[0].LustreConfiguration.MountName' --output text
```
on the master node and here is the output
```
fsx
```
Does this help you to figure out the FSx problem?
Rangsiman

**Comment by demartinofra** [comment] 2020-04-14 12:19
that looks like the correct expected output. Did cluster creation fail again when mounting FSx?

**Comment by rangsimanketkaew** [comment] 2020-04-14 14:03
I thought that there might be a conflict between the versions of pcluster (2.6.1) and standard AMI that I used to build my own AMI. So I tried creating the cluster again with the latest standard AMI, i.e. ubuntu1804 for us-east-1 `ami-05ff14fd02e80a2ad` and now I have been able to create a cluster with FSx mounted successfully.

Thanks again for your time :)

Rangsiman

**Comment by demartinofra** [comment] 2020-04-14 14:45
No problem! Resolving the issue.

**Closed by demartinofra** 2020-04-14 14:45 UTC
