### ISSUE TITLE
rate exceeded error

### ISSUE THREAD

**Issue by jackyenbioinfo** [aws/aws-parallelcluster#589] opened 2018-10-16 14:26 UTC
Hi cfncluster community,
I keep getting this "Rate exceeded" error while creating my cluster. I am not sure what's wrong. It was working fine few days ago. could someone help me and point me to the right direction? thanks 

cfncluster create testcluster
Beginning cluster creation for cluster: testcluster
Creating stack named: cfncluster-testcluster
Status: MasterServer - CREATE_IN_PROGRESS                                       Rate exceeded

**Comment by sean-smith** [comment] 2018-10-16 18:16
Can you check the status of the stack in the cloudformation console? Just find the stack named `cfncluster-testcluster`. Or run `cfncluster status testcluster`.

This looks like the rate exceeded is coming from our calls to describe stack events, which is how we display the current status of the stack. This doesn't affect the creation of the stack.

You can confirm this by seeing that the stack goes into `CREATE_COMPLETE`.

**Comment by enrico-usai** [comment] 2019-03-04 10:17
We should improve our code by adding an exponential retry in case of "Rate exceeded" exception

**Comment by demartinofra** [comment] 2019-11-28 13:56
Marking as duplicate of https://github.com/aws/aws-parallelcluster/issues/1493 and resolving

**Closed by demartinofra** 2019-11-28 13:56 UTC
Labels: enhancement, help wanted
