### ISSUE TITLE
Wrong Compute Instance Type in Version 2.9.1 CFN Stack Parameter List

### ISSUE THREAD

**Issue by stefan-maxar** [aws/aws-parallelcluster#2212] opened 2020-11-10 20:05 UTC
- AWS ParallelCluster version [e.g. 2.9.0]: 2.9.1
- Cluster Configuration:
```
[cluster AZ-a]
key_name = oracle
base_os = alinux2
master_instance_type = r5.24xlarge
compute_instance_type = c5n.18xlarge
placement_group = DYNAMIC
vpc_settings = AZ-a
master_root_volume_size = 3000
compute_root_volume_size = 30
initial_queue_size = 1
maintain_initial_size = true
max_queue_size = 1
fsx_settings = fs
ebs_settings = gp2
ec2_iam_role = EC2-Cluster-Generation
post_install = [redacted]
s3_read_resource = [redacted]
scheduler = slurm
disable_hyperthreading = true
enable_efa = compute
cw_log_settings = ParallelCluster
#cluster_type = spot
#spot_price = 1.50

[vpc AZ-a]
vpc_id = [redacted]
master_subnet_id = [redacted]
use_public_ips = false
vpc_security_group_id = [redacted]

[fsx fs]
shared_dir = [redacted]
storage_capacity = 14400
imported_file_chunk_size = 1024
import_path = [redacted]
deployment_type = SCRATCH_2

[ebs gp2]
shared_dir = /shared
volume_type = gp2
volume_size = 3000

[cw_log ParallelCluster]
enable = false
retention_days = 14

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}
```

**Bug description and how to reproduce:**
When creating a cluster from command line (pcluster create) with the above configurations, the compute_instance_type is not being recognized by the main CloudFormation stack during the spin-up process and is set to the default, t2.micro. We have verified this by viewing the status of the CloudFormation stack of the cluster in the AWS console. The "Parameters" tab of the main stack shows the compute instance type as t2.micro rather than c5n.18xlarge - see the attached screenshot.

We have also attempted to re-write our cluster configurations to use the [queue] and [compute_resource] sections with a single queue and compute resource since we are using slurm as our scheduler. The compute instance type still defaulted to t2.micro rather than capturing the instance_type from the [compute_resource] section.

This does not seem to impact the actual instance type coming up, however, as the instance type in being created via EC2 console shows the correct type, c5n.18xlarge. Just a rather confusing bug that made it seem that even though we requested c5n.18xlarge, the stack made it seem like we were bringing up t2.micro.

**Additional context:**
Screenshot:
![Pcluster_stack](https://user-images.githubusercontent.com/57150975/98724299-8d0a6280-2361-11eb-8b1e-e5cc5629e8a9.png)

**Comment by stefan-maxar** [comment] 2020-11-10 22:29
Following up on this - it also looks like the EFA parameter from the main stack (EFA) also only takes "NONE" even if enable_efa = compute in the configurations.

**Comment by tilne** [comment] 2020-11-11 23:52
Hi, @stefan-maxar.

What you're observing here is a consequence of a change we made in v2.9.0 to the cluster configuration model for slurm clusters, in order to add support for heterogeneous instance types.

> We have also attempted to re-write our cluster configurations to use the [queue] and [compute_resource] sections with a single queue and compute resource since we are using slurm as our scheduler. The compute instance type still defaulted to t2.micro rather than capturing the instance_type from the [compute_resource] section.

This is expected. Starting in 2.9.0, configuration files specifying slurm as the scheduler and using the 'old model' are converted internally to the same representation used for configuration files using slurm as the scheduler and using the 'new model' (queues, compute_resources, etc.).

> This does not seem to impact the actual instance type coming up, however, as the instance type in being created via EC2 console shows the correct type, c5n.18xlarge. Just a rather confusing bug that made it seem that even though we requested c5n.18xlarge, the stack made it seem like we were bringing up t2.micro.

This is because the ComputeFleetHITSubstack doesn't use any of these parameters. It's generated dynamically by the CLI and then uploaded to `${ResourcesS3Bucket}/templates/compute-fleet-hit-substack.rendered.cfn.yaml`, where ResourcesS3Bucket is set to the value of the CFN parameter by the same name. The data used to generate the template can be found in the same bucket at the key `configs/cluster-config.json`. Here's what that object contained for a cluster I created using a similar config as yours:
```json
{
  "cluster": {
    "label": "AZ-a",
    "scaling": {
      "label": "default",
      "scaledown_idletime": 10
    },
    "default_queue": "compute",
    "queue_settings": {
      "compute": {
        "compute_type": "ondemand",
        "enable_efa": true,
        "disable_hyperthreading": true,
        "placement_group": "DYNAMIC",
        "compute_resource_settings": {
          "default": {
            "instance_type": "c5n.18xlarge",
            "min_count": 1,
            "max_count": 1,
            "initial_count": 1,
            "spot_price": 0,
            "vcpus": 36,
            "gpus": 0,
            "enable_efa": true,
            "disable_hyperthreading": true,
            "disable_hyperthreading_via_cpu_options": true
          }
        }
      }
    },
    "disable_cluster_dns": false
  }
}
```
You'll notice that `enable_efa` is true and `instance_type` is set to the correct value based on the config.

All that said, sorry about the confusion. Did this break some automation you had built on top of the stack's CFN paramters?

**Comment by stefan-maxar** [comment] 2020-11-12 14:32
Yes, it did - we had some logic based on those parameters. Specifically, detecting if EFA was enabled upon cluster spin-up in order to properly set some environmental parameters during our post-install procedures. Is the preferred method for pulling such details now to get the cluster information from S3 as in your example? From our end, it would be ideal for these to also be in the main CFN stack parameters, or removed completely from the CFN stack parameter list to avoid the confusion.

**Comment by tilne** [comment] 2020-11-12 17:02
> Yes, it did - we had some logic based on those parameters. Specifically, detecting if EFA was enabled upon cluster spin-up in order to properly set some environmental parameters during our post-install procedures.

Sorry about that. We don't promise to avoid breaking changes on the CFN parameters/outputs, but we try to avoid it whenever possible because we're aware that users such as yourselves treat it as a kind of API. Unfortunately the configuration model for multiple queues, each of which potentially contains multiple instances types, doesn't map to the existing CFN parameters in the same way the single compute instance type configuration model does.

> Is the preferred method for pulling such details now to get the cluster information from S3 as in your example?

Yes, for clusters using slurm as the scheduler.

> From our end, it would be ideal for these to also be in the main CFN stack parameters, or removed completely from the CFN stack parameter list to avoid the confusion.

Those parameters are still required for the other supported schedulers, so we can't remove them.

**Comment by tilne** [comment] 2020-11-12 17:05
I'm going to close this because I believe we've covered the root cause of your issue.

If you think there's more to cover here, please re-open and we'll do so.

**Closed by tilne** 2020-11-12 17:05 UTC

**Comment by stefan-maxar** [comment] 2020-11-18 18:51
@tilne Going to re-open this to provide some more feedback now that 2.10.0 is released. Since we use post-install scripts to prepare our runtime environment (create/update .bashrc files, etc.) its useful to have some of the pertinent cluster configurations (e.g., is EFA enabled?) housed somewhere that won't change ParallelCluster version to version. Our current logic uses the /etc/parallelcluster/cfnconfig file (sourced in post install) combined with describing the stack by the stack name defined the that cfnconfig file. An example of determining if EFA is enabled below.

In versions 2.8.X - grabbing if EFA was enabled was a simple one-liner:
```
efa_parameter=$(aws cloudformation describe-stacks --stack-name $stack_name --region $cfn_region | jq -r '.Stacks[0].Parameters[] | select(.ParameterKey == "EFA") | .ParameterValue') || exit 1
```

Which evolved in 2.9.X to:
```
stack_s3=$(aws cloudformation describe-stacks --stack-name $stack_name --region $cfn_region | jq -r '.Stacks[0].Parameters[] | select(.ParameterKey == "ResourcesS3Bucket") | .ParameterValue') || exit 1

aws s3 cp s3://${stack_s3}/configs/cluster-config.json . || exit 1

efa_parameter=$(jq -r '.cluster.queue_settings[].enable_efa' cluster-config.json)
```

Which now, changed again to accommodate 2.10.0:
```
stack_s3=$(aws cloudformation describe-stacks --stack-name $stack_name --region $cfn_region | jq -r '.Stacks[0].Parameters[] | select(.ParameterKey == "ResourcesS3Bucket") | .ParameterValue') || exit 1

resource_s3=$(aws cloudformation describe-stacks --stack-name $stack_name --region $cfn_region | jq -r '.Stacks[0].Parameters[] | select(.ParameterKey == "ArtifactS3RootDirectory") | .ParameterValue') || exit 1
  
aws s3 cp s3://${stack_s3}/${resource_s3}/configs/cluster-config.json . || exit 1

efa_parameter=$(jq -r '.cluster.queue_settings[].enable_efa' cluster-config.json)
```
So in a matter of 3 releases, an API-like one-line command with one point of failure becomes a series of API-like transactions with multiple points of failure (need for CloudFormation, S3). Given that each evolution of ParallelCluster tends to change how these parameters are defined and where they are housed, I'd like to work with you and the team to come up with a way that houses these relevant parameters in a manner that is not impacted release-to-release (unless intentionally so) and that is more readily transparent so that we downstream can leverage them in our logic. A lot of what we do is automated cluster spin-up/down, so we rely heavily on logic built around cluster configurations.

Perhaps these parameters are all put into the /etc/parallelcluster/cfnconfig file that has been around since the early days (and prior to) ParallelCluster. Or perhaps, a dynamoDB stores all the relevant cluster configuration parameters. Just throwing some ideas out there - hopefully we can find a happy middle ground that works for all users!

Thanks! Stefan
