### ISSUE TITLE
when i used aws-parallelcluster 3.7.2 build-image the  cloudformation  DELETE_FAILED

### ISSUE THREAD

**Issue by csy97** [aws/aws-parallelcluster#5789] opened 2023-10-26 09:23 UTC
When I use pcluster build-image, the AMI is successfully created, but there is an error during resource cleanup, I see from cloudtrail that the reason for the error is that the CleanupLambdaRole created by default does not have the getrole, ListAttachedRolePolicies ListRolePolicies and so on.
But I don't have this problem in version 3.6.1, I can reproduce this problem stably with the following commands and configuration file
pcluster build-image --image-configuration image-config.yaml --image-id testpcluster361

(pvenv) [root@AWS-CLI pcluster-test]# cat image-config.yaml
Build:
  InstanceType: c5.4xlarge
  ParentImage: ami-0b48ec38e7bb9f2d1
  SubnetId: subnet-01b7fa5bfe747ecce
  SecurityGroupIds:
    - sg-0f7e41c74de8b5dd9

**Comment by csy97** [comment] 2023-10-27 04:14
Does this have anything to do with me being at BJS?

**Comment by joehellmersNOAA** [comment] 2023-11-02 12:19
I have the same problem.

**Comment by csy97** [comment] 2023-11-03 05:51
> I have the same problem.
I specified a CleanupLambdaRole in the template and the problem could be solved

# trust relation
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "lambda.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}

#policy
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"，
				"iam:DeleteRole",
				"iam:DetachRolePolicy",
				"iam:DeleteInstanceProfile",
				"iam:DeleteRolePolicy",
				"iam:RemoveRoleFromInstanceProfile",
				"imagebuilder:DeleteInfrastructureConfiguration",
				"imagebuilder:DeleteComponent",
				"imagebuilder:DeleteComponent",
				"imagebuilder:DeleteImageRecipe",
				"imagebuilder:DeleteDistributionConfiguration",
				"imagebuilder:DeleteImage",
				"imagebuilder:GetImage",
				"imagebuilder:CancelImageCreation",
				"cloudformation:DeleteStack",
				"ec2:CreateTags",
				"tag:TagResources",
				"lambda:DeleteFunction",
                "lambda:RemovePermission",
				"logs:DeleteLogGroup",
                "SNS:GetTopicAttributes",
                "SNS:DeleteTopic",
                "SNS:Unsubscribe"
            ],
            "Resource": "*"
        }
    ]
}

But I still don't know why my stack deletion failed

**Comment by enrico-usai** [comment] 2023-11-06 07:53
Hi everyone, this is a "known" issue, due to some changes in the ImageBuilder service that they are reverting back.
The issue shouldn't impact AMI creation but only deletion of the stack. 
The workaround is to delete it from CloudFormation service, saying to preserve the leftover Role (that doesn't really exist).

**Comment by enrico-usai** [comment] 2024-05-23 16:40
Still valid, but resolving as duplicate of: https://github.com/aws/aws-parallelcluster/issues/5914

**Closed as completed by enrico-usai** 2024-05-23 16:40 UTC
Labels: 3.x
