### ISSUE TITLE
Support for multiple-instance types mapped into partitions

### ISSUE THREAD

**Issue by steveisoft** [aws/aws-parallelcluster#1448] opened 2019-11-12 14:16 UTC
We are using parallelcluster w/ slurm, but have a requirement for multiple ComputeFleets that are mapped into slurm partitions, so we can distribute the various kinds of jobs.

Yes, we could use multiple clusters, but this is dissimilar to our existing non-cloud environment, and is considered unacceptable overhead.

**Comment by sean-smith** [comment] 2019-11-12 18:53
@steveisoft Thanks for the feature request!

**Comment by sean-smith** [comment] 2019-11-18 16:29
Duplicate of https://github.com/aws/aws-parallelcluster/issues/1066

**Closed by sean-smith** 2019-11-18 16:29 UTC
Labels: enhancement
