### ISSUE TITLE
--tags not inherited to compute nodes, just master nodes (Feature Request)

### ISSUE THREAD

**Issue by alexiswl** [aws/aws-parallelcluster#2247] opened 2020-11-17 11:03 UTC
We use the `--tags` parameter when running `pcluster create` to ensure that all of our instances have an identifiable owner or service user associated with them.  

While the master instance id inherits the tags set by the `pcluster create` cli, the compute nodes do not.  

Although this would be technically possible to add through the pre-install/post-install with some messy `jq` logic, 
can we request that `--tags` is inherited by both the master and any compute nodes that are launched throughout the duration of the cluster?

**Comment by brainstorm** [comment] 2020-11-18 03:42
Indeed, for billing purposes (among others) this can help a lot.

**Comment by ddeidda** [comment] 2020-11-18 14:25
@alexiswl 

Your feature request should already be satisfied by [this patch](https://github.com/aws/aws-parallelcluster/pull/2113/files). The new behavior will be supported by the next version of ParallelCluster. Thanks for your contribution!

**Comment by demartinofra** [comment] 2020-11-18 15:50
Duplicate of https://github.com/aws/aws-parallelcluster/issues/2100. The linked issue also contains a temporary workaround while this gets addressed in the upcoming release

**Closed by demartinofra** 2020-11-18 15:50 UTC
Labels: pending release
