### ISSUE TITLE
Cannot connect to pcluster instance - times out.

### ISSUE THREAD

**Issue by firth-l** [aws/aws-parallelcluster#3866] opened 2022-03-08 23:34 UTC
When I try to connect to my pcluster instance, it times out and says: 

> ERROR: Something went wrong during DCV connection.
> ssh: connect to host 34.210.142.169 port 22: Connection timed out
> Please check the logs in the /var/log/parallelcluster/ folder of the master instance and submit an issue https://github.com/aws/aws-parallelcluster/issues

So I try to ssh to it and also get a time out.  I'm afraid I might have filled my disk running an application but not sure.  Thanks in advance for any help!

Lee

**Comment by enrico-usai** [comment] 2022-03-14 12:20
Hi Lee,

I'm going to close this ticket since we're following through AWS Support ticketing system.

Just as a reference we've been able to detect the root cause of the issue after providing head node instance id.

Enrico

**Closed as completed by enrico-usai** 2022-03-14 12:20 UTC
