### ISSUE TITLE
question : how to specify AMI in  configuration file 

### ISSUE THREAD

**Issue by binzhougithub** [aws/aws-parallelcluster#2208] opened 2020-11-10 01:23 UTC
I apologize if it is not right place to ask question or new feature request. 

PCluster is using "aws ssm get-parameters-by-path --path /aws/service/ami-amazon-linux-latest" to get a AMI, and uses this AMI to fetch some information by dryrun mode.   nothing wrong about this pcluster behavior,  unfortunately, our company remains a AMI whitelist,   every AMI must be approved in our company.   the 'latest' AMI for the above CLI is changed monthly.  I wonder if you could tell me the work around, for example  pcluster uses AMI specified in configuration file( custom_ami is in my configuration file, not sure if custom_ami 
 is a good replacement)  instead of using the above CLI

Thanks

**Comment by tilne** [comment] 2020-11-10 21:22
Hello, binzhougithub.

> I apologize if it is not right place to ask question or new feature request.

You're in the right place!

> ... our company remains a AMI whitelist, every AMI must be approved in our company. the 'latest' AMI for the above CLI is changed monthly. I wonder if you could tell me the work around...

We are aware of this shortcoming in our product. We have plans to address it, as we know a lot of customers like yourself work in environments that prevent the use of non-sanctioned AMIs, even for the dry run. Unfortunately, we haven't had the time to address it yet.

For a workaround, you can set the following in your cluster configuration file:
```ini
[global]
sanity_check = false
```
When disabling sanity_check in this way, the validator that makes the dry run call will still run (and print an error message if it fails due to not being able to use the AMI) but the creation process will continue.

I believe this is a duplicate of #1822. Given that I'm going to mark this as a duplicate and close it, and you can follow the other issue. If you think this issue is different, or if there's an issue with the workaround I recommended, please re-open this issue.

**Closed by tilne** 2020-11-10 21:22 UTC
