### ISSUE TITLE
Compute ready command failing

### ISSUE THREAD

**Issue by sentient-kshaffer** [aws/aws-parallelcluster#590] opened 2018-10-16 20:25 UTC
When my compute nodes were done initializing, the `/opt/cfncluster/scripts/compute_ready` script was failing with the message:

```
2018-10-16 20:07:47,355 [DEBUG] Command compute_ready output: Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 17, in <module>
    import botocore.session
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 27, in <module>
    import botocore.credentials
  File "/usr/local/lib/python2.7/dist-packages/botocore/credentials.py", line 42, in <module>
    from botocore.utils import InstanceMetadataFetcher, parse_key_val_file
  File "/usr/local/lib/python2.7/dist-packages/botocore/utils.py", line 31, in <module>
    import botocore.httpsession
  File "/usr/local/lib/python2.7/dist-packages/botocore/httpsession.py", line 16, in <module>
    from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
  File "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

2018-10-16 20:07:47,355 [ERROR] Error encountered during build of signalComputeReady: Command compute_ready failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command compute_ready failed
2018-10-16 20:07:47,357 [ERROR] -----------------------BUILD FAILED!------------------------
2018-10-16 20:07:47,357 [ERROR] Unhandled exception during build: Command compute_ready failed
Traceback (most recent call last):
  File "/usr/local/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command compute_ready failed
```

I was able to do a work around manually after sshing into my compute node:
```
$ sudo rm -rf /usr/lib/python2.7/dist-packages/OpenSSL
$ sudo rm -rf /usr/lib/python2.7/dist-packages/pyOpenSSL-0.15.1.egg-info
$ sudo pip install pyopenssl
$ /opt/cfncluster/scripts/compute_ready
```

This workaround shouldn't be necessary though. 
I do have a long post-install script running on my compute nodes, but even when I ran the `compute_ready` script manually it still wasn't working with the same error until I did my workaround.

**Comment by enrico-usai** [comment] 2018-10-17 08:41
Hi @sentient-kshaffer could you give us more details? 
- the CfnCluster version
- the configuration (what os?)

Then could you try without the post install script and see if the problem is related to it?

**Comment by chrisdag** [comment] 2018-10-31 18:49
Saw this error myself today with cfncluster 1.6.1 -- the only fix that worked was to update our custom AMI after running the "pip install --upgrade pyopenssl" command -- something in pyopenssl is not happy with the final node provisioning script steps

**Comment by sentient-kshaffer** [comment] 2018-11-08 13:12
@enrico-usai The version I was using was 1.5.4, and the base_os was ubuntu1604.

**Comment by enrico-usai** [comment] 2018-11-20 17:42
Thank you @sentient-kshaffer for the OS information. 
@chrisdag can you confirm are you using the same OS?

We suppose it is a dependency problem related to the OS, similar to the one fixed by https://github.com/aws/aws-parallelcluster-cookbook/pull/219

**Comment by lukeseawalker** [comment] 2019-02-01 10:35
We fixed many dependency issues since that version.
I suggest you to update to the latest and let us know if you still have the issue.

**Closed by lukeseawalker** 2019-02-01 10:35 UTC
Labels: bug
