### ISSUE TITLE
Adding EBS with snapshot creates error

### ISSUE THREAD

**Issue by rajiv03** [aws/aws-parallelcluster#1335] opened 2019-09-27 20:29 UTC
When i use attaching EBS, i get  following error. If I dont attach EBS, it creates fine.

R-MacBook-Pro:~w$ pcluster create testHPC --norollback
Beginning cluster creation for cluster: testHPC
Creating stack named: parallelcluster-testHPC
Status: parallelcluster-testHPC - CREATE_FAILED                                
Cluster creation failed.  Failed events:
  - AWS::CloudFormation::Stack parallelcluster-testHPC The following resource(s) failed to create: [MasterServerWaitCondition, ComputeFleet]. 
  - AWS::AutoScaling::AutoScalingGroup ComputeFleet Resource creation cancelled
  - AWS::CloudFormation::WaitCondition MasterServerWaitCondition Failed to receive 1 resource signal(s) within the specified duration

[aws]
aws_region_name = us-east-1
aws_access_key_id = xxxxx- removed
aws_secret_access_key =xxxxx- removed

[cluster default]
key_name =xxxxx- removed
vpc_settings = public
max_queue_size = 50
initial_queue_size = 20
master_instance_type = c5n.xlarge
compute_instance_type = c5n.18xlarge
cluster_type = spot
scaling_settings = custom
#scheduler = torque
s3_read_write_resource = arn:aws:s3:::xxxxx- removed*
ebs_settings = data_all
placement_group = DYNAMIC

[scaling custom]
scaledown_idletime = 10

[vpc public]
vpc_id = vpc-xxxxx- removed
master_subnet_id = subnet-xxxxx- removed

[ebs data_all]
ebs_snapshot_id = snap-xxxxx- removed
ebs_volume_id = vol-xxxxx- removed
 

[global]
cluster_template = default
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

excuted with `--norollback` option and attached `/var/log/cfn-init.log`, `/var/log/cloud-init.log` and `/var/log/cloud-init-output.log` files from the Master node

[cloud-init-output.log](https://github.com/aws/aws-parallelcluster/files/3664411/cloud-init-output.log)
[cloud-init.log](https://github.com/aws/aws-parallelcluster/files/3664412/cloud-init.log)

**Comment by enrico-usai** [comment] 2019-09-30 16:28
Hi @rajiv03 

I'm marking this as a bug, since there are multiple users having issues with snapshots:
https://github.com/aws/aws-parallelcluster/issues/1325
https://github.com/aws/aws-parallelcluster/issues/614

**Comment by rajiv03** [comment] 2019-10-01 07:38
Thanks for tagging it as bug.
I've tried attaching exisiting ebs using snapshot or voulme id but still not able to pass the installation. (alinux,centos and ubuntu1604 gives same error).

Note that exisiting ebs shown to be attached in Master Block devices as /dev/sdb but not able to see it in when ssh to Master.


Few lines error from cfn-init-cmd.log

2019-10-01 06:47:07,226 P1851 [INFO] 	---- Begin output of mount -t gpt -o _netdev /dev/disk/by-ebs-volumeid/vol-0e42fd1f71370a8a2 /shared ----
2019-10-01 06:47:07,226 P1851 [INFO] 	STDOUT: 
2019-10-01 06:47:07,226 P1851 [INFO] 	STDERR: mount: unknown filesystem type 'gpt'
2019-10-01 06:47:07,226 P1851 [INFO] 	---- End output of mount -t gpt -o _netdev /dev/disk/by-ebs-volumeid/vol-0e42fd1f71370a8a2 /shared ----
2019-10-01 06:47:07,226 P1851 [INFO] 	Ran mount -t gpt -o _netdev /dev/disk/by-ebs-volumeid/vol-0e42fd1f71370a8a2 /shared returned 32
2019-10-01 06:47:07,226 P1851 [INFO] 	[2019-10-01T06:47:07+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: mount[/shared] (aws-parallelcluster::_master_base_config line 85) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '32'
2019-10-01 06:47:07,226 P1851 [ERROR] Exited with error code 1

**Comment by lukeseawalker** [comment] 2019-10-04 16:03
I'm closing this because duplicate of https://github.com/aws/aws-parallelcluster/issues/614

**Closed by lukeseawalker** 2019-10-04 16:03 UTC
Labels: bug
